version: '3.8'
services:

  butovo_les:
    image: rudiwork/butovo_les:1
    volumes:
      - butovo-les-public:/app/public
    working_dir: /app
    environment:
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_CLI_ENABLE: 1
      APP_ENV: prod
      TO_EMAIL: ${TO_EMAIL}
      GOOGLE_RECAPTCHA_SITE_KEY: ${GOOGLE_RECAPTCHA_SITE_KEY}
      GOOGLE_RECAPTCHA_SECRET: ${GOOGLE_RECAPTCHA_SECRET}
    user: www-data:www-data
    networks:
      - nginx-proxy
      - butovo-les-internal

networks:
  butovo-les-internal:
    internal: true
  nginx-proxy:
    external: true

volumes:
  butovo-les-public:
    external: true
